### ISSUE TITLE
[0.4.10] Export to Markdown Weird in Discord

### ISSUE THREAD

**Issue by wyrdR** [314r-app/pf2eBattleTracker_issues#13]
Great app!

Just some small problems with __Play by Discord__.

A single underscore either side of line triggers _italic_ text.

A double underscore triggers __underline__.

This ends up looking pretty odd.

Examples below:

With `___` separators: 

![Screenshot_20240505-205549-906~2](https://github.com/314r-app/pf2eBattleTracker_issues/assets/7156785/e6bee3ab-82b3-4841-b418-31e684fcae8b)

Suggested seperator:
`—`

Generated code: 
 
```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 
___ 
**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10 
___ 
**Ezren** | HP: 41/53 |
___ 
:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2 
___ 
**Giant Dragonfly** | HP: 60/60 |
AC: 21 Fort: 12 Ref: 14 Will: 9 
2d6 persistent Fire damage (10rd)
___ 
**Merisiel** | HP: 56/56 |
___ 
**Grippli Greenspeaker** | HP: 71/71 |
AC: 21 Fort: 10 Ref: 13 Will: 13 
___ 
**Kyra** | HP: 48/48 |
Stunned 1 
___ 
**Grippli Archer (1)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 
___ 

```

With suggested seperator:

![Screenshot_20240505-210325](https://github.com/314r-app/pf2eBattleTracker_issues/assets/7156785/ee1e8c5a-611f-4a70-a248-1f65f3ddc5d8)

Suggested code:
```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 
— 
**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10 
— 
**Ezren** | HP: 41/53 |
— 
:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2 
— 
**Giant Dragonfly** | HP: 60/60 |
AC: 21 Fort: 12 Ref: 14 Will: 9 
2d6 persistent Fire damage (10rd)
— 
**Merisiel** | HP: 56/56 |
— 
**Grippli Greenspeaker** | HP: 71/71 |
AC: 21 Fort: 10 Ref: 13 Will: 13 
— 
**Kyra** | HP: 48/48 |
Stunned 1 
— 
**Grippli Archer (1)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 
— 
```

Or maybe there's a better option for horizontal lines in Discord?

**Comment by wyrdR** [comment]
Surrounding the ___ with `backquotes` does the trick…

*But* I think this might break other applications .

**Comment by 314r-app** [comment]
Hello and thank you for the bug report. I didn't know that Discord do not use exactly the markdown standard. 3 underscores is supposed to display an horizontal line in Markdown, not just `___`, as in the image below:

![Screenshot 2024-05-05 at 15-48-25 StackEdit](https://github.com/314r-app/pf2eBattleTracker_issues/assets/127806919/2692764f-2f25-4c1a-b608-02b8c25d9c39)

But in discord it seems to consider the underscore only as the tag for underlining, even after a line break. I didn't find a way to make nice horizontal line on Discord text message, so I went with `---` which is also displaying a horizontal line in normal markdown, and display just `---` in Discord. 

I pushed the new version 0.4.11 with this change. It should be available to download in few hours when the playstore page will update.

**Comment by wyrdR** [comment]
## Ah, what are standards for but to ignore? 😂

I'm pretty sure this has been pointed out to Discord over the years. ¯\_(ツ)_/¯

Thanks heaps for that; very prompt!

But there is now a blank line between every dashed line.

See below:

```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10

---

**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10

---

**Ezren** | HP: 41/53 |

---

:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2

---

…
```

I think it's more compact without the extra spaces. For example:

```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10
---
**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10
---
**Ezren** | HP: 41/53 |
---
:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2
---
…
```

Thanks,

@wyrdR

**Comment by wyrdR** [comment]
_Email messed formatting up…._


But there is now a blank line between every dashed line.

See below:

```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 

--- 

**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10 

--- 

**Ezren** | HP: 41/53 |

--- 

:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2 

--- 

…
```
_Result_
![Screenshot_20240506-140955](https://github.com/314r-app/pf2eBattleTracker_issues/assets/7156785/f42f9347-d545-4b63-b015-278d2d4c8d77)

     
I think it's better to be more compact like this:  

```
## Round 2, turn of : Valeros
**Grippli Archer (2)** | HP: 44/44 |
AC: 20 Fort: 9 Ref: 11 Will: 10 
--- 
**Grippli Archer** | HP: 10/44 | *Critically wounded* |
AC: 20 Fort: 9 Ref: 11 Will: 10 
--- 
**Ezren** | HP: 41/53 |
--- 
:star: **Valeros** | HP: 38/78 | *Wounded* |
Frightened 2 
--- 
…
```

**Comment by 314r-app** [comment]
Yes, the blank lines before and after are required to make it work with standard Markdown.

What I could do is add an option in the dialog before exporting to select a "discord format" and remove this lines in this case.

**Comment by wyrdR** [comment]
That sounds good to me.

@wyrdR

**Comment by wyrdR** [comment]
How about something like this for an ultra-compact output?

```
## Round 1, turn of : Poppy

- ⭐ **Poppy** | HP: 18/18 |
  - AC: 15 Fort: 5 Ref: 5 Will: 8 
- **Bepoe** | HP: 11/14 |
  - AC: 18 Fort: 3 Ref: 9 Will: 5 
  - Sickened 1, Hidden
- ~~**Young Sea Serpent A**~~ | HP: 0/20 :skull_and_crossbones:
- ~~**Young Sea Serpent B**~~ | HP: 0/20 :skull_and_crossbones: 
- **Hands** | HP: 19/25 |
  - AC: 15 Fort: 8 Ref: 6 Will: 3 
- **Refur** | HP: 16/16 |
  - AC: 16 Fort: 5 Ref: 8 Will: 6
```

___

## Round 1, turn of : Poppy

- ⭐ **Poppy** | HP: 18/18
  - AC: 15 Fort: 5 Ref: 5 Will: 8 
- **Bepoe** | HP: 11/14 |
  - AC: 18 Fort: 3 Ref: 9 Will: 5 
  - Sickened 1, Hidden
- ~~**Young Sea Serpent A**~~ | HP: 0/20 ☠️ 
- ~~**Young Sea Serpent B**~~ | HP: 0/20 ☠️
- **Hands** | HP: 19/25 |
  - AC: 15 Fort: 8 Ref: 6 Will: 3 
- **Refur** | HP: 16/16 |
  - AC: 16 Fort: 5 Ref: 8 Will: 6

**Comment by wyrdR** [comment]
This also looks neat. That's an endash `–` before HP  which I like for clean, simple separators.

Also, since they're modifiers, saving throws should usually be prefixed with `+` or `-`

- ⭐ **Chungus** – HP 11/18
  - AC 15 Fort +5 Ref +5 Will +8

**Comment by 314r-app** [comment]
Ok i'm noting that. I will put the +/- for the saves in any case. 

For replacing the horizontal line delimitation with a bullet point list, I will add a setting "Compact format" to select or not. I will take care of this in the next days.

**Comment by 314r-app** [comment]
Hello, I added new options in the menu to export to markdown:
* Compact format
* Group initiative
* Use Emojis

I also added "Display reaction" for PC or NPC.

Here is an example of the "compact format" rendered on Discord. What do you think about it ?

![compact](https://github.com/314r-app/pf2eBattleTracker_issues/assets/127806919/26edc6e0-e156-47d5-85b3-61fa3f5a051b)

**Comment by wyrdR** [comment]
Looks awesome. 
Great work.

**Comment by 314r-app** [comment]
Thank you, I'm closing the issue.
