### ISSUE TITLE
status penalties shouldn't stack

### ISSUE THREAD

**Issue by neilneely** [314r-app/pf2eBattleTracker_issues#18]
To reproduce: 
Add Frightened 2 condition to a creature
Add Clumsy 3 condition to that creature
AC should be -3 because Clumsy and Frightened are both status penalties

The app currently makes the AC -5, and that is incorrect.
https://2e.aonprd.com/Conditions.aspx?ID=76
https://2e.aonprd.com/Conditions.aspx?ID=61

**Comment by 314r-app** [comment]
Hello and thank you for the report. You are right it shouldn't stack. I am adding that to my urgent todolist.

**Comment by 314r-app** [comment]
Fixed in version 0.4.15. Sorry for the long wait I had a busy month.
