### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by Laky099** [314r-app/pf2eBattleTracker_issues#4]
It would be great to have a small line below the name with the conditions and the eventual Persistent Damage (It would be great if the Persistent Damage would be self rolled when the turn starts, even automatically lowing down HP).
Anyway great job!

**Comment by 314r-app** [comment]
Hello and thank you for your feedback. This is indeed to major next feature that I am working on. On top of the implementation needed there is also some design choices where I am still not fully sure about which option to take. 

You can check my current plan and description here https://github.com/314r-app/pf2eBattleTracker_issues/issues/3.
