### ISSUE TITLE
Character name is incorrect after changing their initiative manually

### ISSUE THREAD

**Issue by braveleg** [314r-app/pf2eBattleTracker_issues#7]
Reproduce scenario
1. Have 4 differenly named characters in an encounter
2. Manually change initiative of the first character so it is between 2 and 3 character now
3. Check names

Expected result:
First character is correctly moved in the initiative order without changing his name

Actual result:
Character is moved, but his name is changed to the character's name that was there before (so it's duplicated now)

**Comment by 314r-app** [comment]
Thank you for the bug report, it looks like I introduced that bug recently. The data were correct but the interface was not updating correctly, so the unit tests didn't detect any issues. 

I fixed it, it will be in the next release (0.2.6 for the main branch, 0.3.0 in the beta branch). It should be available on the playstore by end of the day.

**Comment by braveleg** [comment]
Thanks for the quick fix, appreciate it 👍

**Comment by 314r-app** [comment]
The update is live.
