### ISSUE TITLE
Persistant damage  output bugged

### ISSUE THREAD

**Issue by swaters83** [314r-app/pf2eBattleTracker_issues#9]
Let me preface this, I'm using a tablet. When persistent damage happens the box that pops up seems cut off and you can't do anything but go back, 
![Screenshot_20231101_193628_BattleTracker Pathfinder 2e](https://github.com/314r-app/pf2eBattleTracker_issues/assets/11818387/3fe41222-1a07-4e51-9409-40538542e548)

**Comment by 314r-app** [comment]
Hello, sorry for this error. I didn't notice it in the tablet emulator. Could you please specify your screen size and resolution (or just tablet model) ?

**Comment by swaters83** [comment]
![Screenshot_20231102_061234_Shop Samsung](https://github.com/314r-app/pf2eBattleTracker_issues/assets/11818387/52159488-161b-42b0-9979-eb1c2980154d)

**Comment by 314r-app** [comment]
Ok, I could reproduce it in the emulator. I will work on it.

**Comment by 314r-app** [comment]
Fixed in version 0.4.5, it will be live in a couple of hours.
